# Generated by Django 4.0.4 on 2022-05-21 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('isCreep', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1_order', models.IntegerField()),
                ('v1_mark', models.IntegerField()),
                ('v2_order', models.IntegerField()),
                ('v2_mark', models.IntegerField()),
                ('v3_order', models.IntegerField()),
                ('v3_mark', models.IntegerField()),
                ('v1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=500)),
                ('mark', models.IntegerField()),
                ('price', models.IntegerField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.director')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
